### ISSUE TITLE
Problem installing module

### ISSUE THREAD

**Issue by austineinstein** [edwardpopoola/pypaystack#2]
<img width="1202" alt="screen shot 2018-03-23 at 04 50 06" src="https://user-images.githubusercontent.com/12557036/37812247-f419bab4-2e56-11e8-92dd-fbcca8d80ed7.png">

**Comment by edwardpopoola** [comment]
Ensure your python version is >= 3.0

**Comment by Michael-Lyon** [comment]
Please how do I make use of Ur module. And also record some payment info in
my backend.
